#!.venv/bin/python3
import os
from argparse import ArgumentParser
import subprocess
import shutil

parser = ArgumentParser()
parser.add_argument('number')
args = parser.parse_args()
concat = 'concat:'

if os.path.exists('intermediate'):
    shutil.rmtree('intermediate')
os.mkdir('intermediate')
for i in range(len(os.listdir(f'media/{args.number}'))):
    concat += f'intermediate/{i}.ts|'
    subprocess.run(['ffmpeg', '-i', f'media/{args.number}/media{i}.mp4', '-c', 'copy', f'intermediate/{i}.ts'])
concat = concat[:-1]

subprocess.run(['ffmpeg', '-i', concat, '-c', 'copy', 'output.mp4'])