#!.venv/bin/python3

from transformers import AutoImageProcessor, DetrForObjectDetection
import torch
from PIL import Image
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument("image", nargs="?", help="file path of the image to be scanned")
args = parser.parse_args()
if args.image:
    image = Image.open(args.image).convert("RGB")
else:
    image = Image.open("image.png").convert("RGB")

image_processor = AutoImageProcessor.from_pretrained("facebook/detr-resnet-50")
model = DetrForObjectDetection.from_pretrained("facebook/detr-resnet-50")

inputs = image_processor(images=image, return_tensors="pt")
outputs = model(**inputs)

# convert outputs (bounding boxes and class logits) to Pascal VOC format (xmin, ymin, xmax, ymax)
target_sizes = torch.tensor([image.size[::-1]])
results = image_processor.post_process_object_detection(outputs, threshold=0.9, target_sizes=target_sizes)[
    0
]

for score, label, box in zip(results["scores"], results["labels"], results["boxes"]):
    box = [round(i, 2) for i in box.tolist()]
    print(
        f"Detected {model.config.id2label[label.item()]} with confidence "
        f"{round(score.item(), 3)} at location {box}"
    )