#!.venv/bin/python3

import cv2
from tqdm import tqdm
import subprocess
import os
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument("inputfile", type=str, help="input video mp4 or image file path to scan")
parser.add_argument("outputfile", type=str, nargs="?", help="output video/image file path")
args = parser.parse_args()


vidreader = cv2.VideoCapture(args.inputfile)
frames = int(vidreader.get(cv2.CAP_PROP_FRAME_COUNT))
fps = vidreader.get(cv2.CAP_PROP_FPS)
shape = (int(vidreader.get(cv2.CAP_PROP_FRAME_WIDTH)), int(vidreader.get(cv2.CAP_PROP_FRAME_HEIGHT)))

intermediate_file = "__inter__.mp4"
vidwriter = cv2.VideoWriter(intermediate_file, cv2.VideoWriter_fourcc(*"mp4v"), fps, shape)
if args.outputfile:
    output_file = args.outputfile
else:
    output_file = "change.mp4"
ret, prev_frame = vidreader.read()
for i in tqdm(range(frames-1)):
    ret, frame = vidreader.read()
    new_frame = prev_frame.copy()
    for r in range(len(frame)):
        for c in range(len(frame[0])):
            if (prev_frame[r][c] == frame[r][c]).all():
                new_frame[r][c] = [0, 0, 0]
    vidwriter.write(new_frame)
    prev_frame = frame
vidwriter.release()
if os.path.exists(output_file):
    os.remove(output_file)
subprocess.run(["ffmpeg", "-i", intermediate_file, output_file])
os.remove(intermediate_file)