#!.venv/bin/python3

import numpy as np
import cv2
import pickle
import subprocess
import os

map_img = cv2.imread("map.png")
height, width, _ = map_img.shape

output_path = "watch.mp4"
intermediate_file = "__inter__.mp4"
vidwriter = cv2.VideoWriter(intermediate_file, fps=15, fourcc=cv2.VideoWriter_fourcc(*"mp4v"), frameSize=(width, height))

with open('geos.pickle', 'rb') as f:
    geos = pickle.load(f)
with open('Hgeo-map.pickle', 'rb') as f:
    H = pickle.load(f)

for geoList in geos:
    img = map_img.copy()
    for geo in geoList:
        dest = [int((geo[0] * H[0][0] + geo[1] * H[0][1] + H[0][2])/(geo[0] * H[2][0] + geo[1] * H[2][1] + H[2][2])),
                int((geo[0] * H[1][0] + geo[1] * H[1][1] + H[1][2])/(geo[0] * H[2][0] + geo[1] * H[2][1] + H[2][2]))]
        cv2.circle(img=img, radius=10, color=[255, 0, 0], center=dest, thickness=-1)    
    vidwriter.write(img)
vidwriter.release()

if os.path.exists(output_path):
    os.remove(output_path)
# the media is corrupt in curtain file editors for whatever reason, running it through ffmpeg fixes this
subprocess.run(["ffmpeg", "-i", intermediate_file, output_path])
os.remove(intermediate_file)